### PR TITLE
Renames gittip to gratipay and updates it

### PR DESCRIPTION
**Pull request by colindean**
- Terms of Service split into Terms of Use and Terms of Service
- Security became a fully qualified page
- Fraud is no longer a page, but was rolled into the others and it supplemented by individual report pages
- Page redesign necessitates new xpath to content location

### CODE REVIEW

**Comment by colindean** [comment]
This will resolve gratipay/gratipay.com#3328.

**Comment by techtonik** [comment]
:+1:

**Comment by pierreozoux** [comment]
@colindean looks like https://gratipay.com/about/policies/terms-and-conditions points to https://gratipay.com/about/policies/terms-of-service

Do you think you could update your PR?

Thanks for your work!

**Comment by colindean** [comment]
And `/about/security` redirects to `https://hackerone.com/gratipay`. Should I adjust that, too?

**Pull request merged**
